image: alpine

stages:
  - deploy

pages:
  stage: deploy
  script:
    - mkdir -p public
    - cp -r * public  # Copier tous les fichiers dans le dossier public
  artifacts:
    paths:
      - public
  only:
    - master  