image: node:latest  # Ou une autre image selon vos besoins

pages:
  script:
    - mkdir public
    - cp -r * public  # Copier les fichiers dans le dossier public
  artifacts:
    paths:
      - public
  only:
    - main  # Modifier si votre branche principale a un autre nom
