image: alpine

stages:
  - deploy

pages:
  stage: deploy
  script:
    - mkdir -p public
    - cp -r * public  # Copier tous les fichiers dans le dossier public
  artifacts:
    paths:
      - public
  only:
    - main  # Remplace "main" si ta branche principale porte un autre nom